/* @flow */
export const APP_LOADED = 'APP_LOADED'
//PRODUCTS
export const LOADING_PRODUCTS = 'LOADING_PRODUCTS'
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const PRODUCTS_LOADED = 'PRODUCTS_LOADED'
export const PRODUCTS_LOAD_ERROR = 'PRODUCTS_LOAD_ERROR'
export const FILTER_PRODUCTS_BY_CATEGORY = 'FILTER_PRODUCTS_BY_CATEGORY'
export const OUT_OF_COVERAGE = 'OUT_OF_COVERAGE'
export const POINT_OF_SALES_LOADED = 'POINT_OF_SALES_LOADED'
//CART
export const ADD_TO_CART = 'ADD_TO_CART'
export const EMPTY_CART = 'EMPTY_CART'
export const CHANGE_CART_COMMENT = 'CHANGE_CART_COMMENT'
export const CART_TOTAL_IS_BELOW_MIN_PRICE = 'CART_TOTAL_IS_BELOW_MIN_PRICE'
export const CART_TOTAL_IS_ABOVE_MIN_PRICE = 'CART_TOTAL_IS_ABOVE_MIN_PRICE'
export const CART_LOADED = 'CART_LOADED'
export const CART_ITEM_INCREASE_AMOUNT = 'CART_ITEM_INCREASE_AMOUNT'
export const CART_ITEM_DECREASE_AMOUNT = 'CART_ITEM_DECREASE_AMOUNT'
export const CART_ITEM_REMOVE = 'CART_ITEM_REMOVE'
export const TOGGLE_CART = 'TOGGLE_CART'
export const HIDE_CART = 'HIDE_CART'
//USER & CONSUMER
//EMAIL LOGIN
export const EMAIL_LOGIN = 'EMAIL_LOGIN'
export const EMAIL_LOGIN_SUCCESS = 'EMAIL_LOGIN_SUCCESS'
export const EMAIL_LOGIN_ERROR = 'EMAIL_LOGIN_ERROR'
//EMAIL REGISTER
export const EMAIL_REGISTER = 'EMAIL_REGISTER'
export const EMAIL_REGISTER_SUCCESS = 'EMAIL_REGISTER_SUCCESS'
export const EMAIL_REGISTER_ERROR = 'EMAIL_REGISTER_ERROR'
//FACEBOOK LOGIN
export const FACEBOOK_REGISTER_SUCCESS = 'FACEBOOK_REGISTER_SUCCESS'
export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS'
export const FACEBOOK_USER_DATA_LOADED = 'FACEBOOK_USER_DATA_LOADED'
//CONSUMER
export const CREATE_CONSUMER = 'CREATE_CONSUMER'
export const CONSUMER_CREATED = 'CONSUMER_CREATED'
export const CONSUMER_LOADED = 'CONSUMER_LOADED'
export const CONSUMER_NOT_FOUND = 'CONSUMER_NOT_FOUND'
export const UPDATE_CONSUMER = 'UPDATE_CONSUMER'
export const CONSUMER_UPDATED = 'CONSUMER_UPDATED'
export const CONSUMER_UPDATE_ERROR = 'CONSUMER_UPDATE_ERROR'
//LOGOUT
export const LOGOUT = 'LOGOUT'
//GEOLOCATION
export const GEOLOCATION_POSITION_ACQUIRED = 'GEOLOCATION_POSITION_ACQUIRED'
export const GEOLOCATION_ERROR = 'GEOLOCATION_ERROR'
export const HIDE_GEOLOCATION_ERROR_MODAL = 'HIDE_GEOLOCATION_ERROR_MODAL'
export const MAP_ADDRESS_CHANGED = 'MAP_ADDRESS_CHANGED'
export const ADDRESS_SAVED = 'ADDRESS_SAVED'
export const ADDRESS_SAVE_ERROR = 'ADDRESS_SAVE_ERROR'
export const MAP_BOUNDS_CHANGED = 'MAP_BOUNDS_CHANGED'
export const ADDRESS_TEXT_CHANGED = 'ADDRESS_TEXT_CHANGED'
export const CONSUMER_ADDRESS_CHANGED = 'CONSUMER_ADDRESS_CHANGED'
export const CONSUMER_ADDRESSES_LOADED = 'CONSUMER_ADDRESSES_LOADED'
export const SET_CURRENT_ADDRESS = 'SET_CURRENT_ADDRESS'
export const CREATE_NEW_ADDRESS = 'CREATE_NEW_ADDRESS'
//MODAL
export const SHOW_MAP_ADDRESS = 'SHOW_MAP_ADDRESS'
export const HIDE_MAP_ADDRESS = 'HIDE_MAP_ADDRESS'
export const SHOW_ADDRESS_FORM = 'SHOW_ADDRESS_FORM'
export const HIDE_ADDRESS_FORM = 'HIDE_ADDRESS_FORM'
export const SHOW_POINT_SALE_CLOSED_MODAL = 'SHOW_POINT_SALE_CLOSED_MODAL'
export const HIDE_POINT_SALE_CLOSED_MODAL = 'HIDE_POINT_SALE_CLOSED_MODAL'
export const SHOW_PROFILE = 'SHOW_PROFILE'
export const HIDE_PROFILE = 'HIDE_PROFILE'
export const HIDE_EMPTY_CART_MODAL = 'HIDE_EMPTY_CART_MODAL'
export const SHOW_EMPTY_CART_MODAL = 'SHOW_EMPTY_CART_MODAL'
export const SHOW_OUT_OF_COVERAGE_MODAL = 'SHOW_OUT_OF_COVERAGE_MODAL'
export const HIDE_OUT_OF_COVERAGE_MODAL = 'HIDE_OUT_OF_COVERAGE_MODAL'
export const HIDE_ADDRESS_SEARCH_MODAL = 'HIDE_ADDRESS_SEARCH_MODAL'
export const SHOW_ADDRESS_SEARCH_MODAL = 'SHOW_ADDRESS_SEARCH_MODAL'
//SIDEBAR
export const SHOW_ADDRESS_LIST = 'SHOW_ADDRESS_LIST'
export const HIDE_ADDRESS_LIST = 'HIDE_ADDRESS_LIST'
//PAYMENT METHOD
export const PAYMENT_METHODS_LOADED = 'PAYMENT_METHODS_LOADED'
export const SELECT_PAYMENT_METHOD = 'SELECT_PAYMENT_METHOD'
export const PAYMENT_NOT_SELECTED = 'PAYMENT_NOT_SELECTED'
export const PAYMENT_SELECTED = 'PAYMENT_SELECTED'
//ORDER
export const CREATE_ORDER = 'CREATE_ORDER'
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR'
export const ORDER_CREATED = 'ORDER_CREATED'
export const SET_CURRENT_ORDER = 'SET_CURRENT_ORDER'
export const UNSET_CURRENT_ORDER = 'UNSET_CURRENT_ORDER'
export const CONSUMER_ORDERS_LOADED = 'CONSUMER_ORDERS_LOADED'
export const RATE_ORDER = 'RATE_ORDER'
export const RATE_ORDER_SUCCESS = 'RATE_ORDER_SUCCESS'
export const RATE_ORDER_ERROR = 'RATE_ORDER_ERROR'
export const RATING_ORDER = 'RATING_ORDER'
//STATES
export const STATE_ACTIVE = 'B8XLBDpbaa'
//Analytics Only
export const LOGIN_SCREEN = 'LOGIN_SCREEN'
export const PRODUCT_DETAIL_SCREEN = 'PRODUCT_DETAIL_SCREEN'
//SITEMAP
export const SHOW_SITEMAP = 'SHOW_SITEMAP'
export const HIDE_SITEMAP = 'HIDE_SITEMAP'

export const CUSTOMER_LOADED = 'CUSTOMER_LOADED'
export const CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND'

export const RENDER_MENU = 'RENDER_MENU'
export const RENDER_ADDRESS_MENU = 'RENDER_ADDRESS_MENU'

export const SET_PAYMENT_METHOD = 'SET_PAYMENT_METHOD'
export const USER_CREDITCARDS_LOADED = 'USER_CREDITCARDS_LOADED'

export const SET_CUSTOMER_POINT_SALE = 'SET_CUSTOMER_POINT_SALE'
export const SET_ORDER = 'SET_ORDER'

export const SET_USER = 'SET_USER'